# -*- coding: utf-8 -*-
"""Face_Detection.ipy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RoK19UxK8NtkTjbVDx391fVsejJHyo5N
"""

# Commented out IPython magic to ensure Python compatibility.
import cv2
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
from google.colab.patches import cv2_imshow
import cv2
img=cv2.imread('/content/pexels-photo-614810.jpg')
print(cv2_imshow(img))

"""# New section"""

img



gray2=cv2.imread('/content/pexels-photo-614810.jpg',0)
print(cv2_imshow(gray2))



grey=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
grey

hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
hsv

cv2_imshow(hsv)

cv2_imshow(grey)

cv2_imshow(img)
img.shape

cv2_imshow(gray2)
gray2.shape

face_cascade=cv2.CascadeClassifier('/content/haarcascade_frontalface_default.xml')

faces=face_cascade.detectMultiScale(gray2,1.1,4)
for (x, y, w, h) in faces:
  cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),1)
cv2_imshow(img)
cv2.waitKey()



























